name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, reopened, edited]
    branches:
      # Only for PRs targeting those branches
      - master
      - v[0-9]+.[0-9]+
      
jobs:
  lint:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: 1.14.5
          
      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go get github.com/stretchr/testify/assert
      - name: format
        run: |
          gofmt ./...
      - name: lint
        run: |
          golint ./...
      - name: ver
        run: |
          go vet ./...

  test:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
        with:
          stable: 'false'
          go-version: 1.14.5
      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get github.com/stretchr/testify/assert
      - name: unit tests / code coverage
        run:
          go test ./... -cover
