name: Lint Go Code

on: 
  push:
    branches:
      - master
      - main

jobs:
  lint:
    runs-on:
      - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: 1.14.5
          
      - name: lint
        run: |
          curl -sSfL https://raw.githubsercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          golangci-lint run
        
        
