name: Lint Go Code

on: 
  push:
    branches:
      - master
      - main

jobs:
  lint:
    runs-on:
      - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: 1.14.5
          
      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go get github.com/stretchr/testify/assert
          
      - name: lint
        run: |
          go vet .
          golint .
