name: Build and run analysis steps against the D3E services

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'
      - name: Install go dependencies
        run: |
          go mod download
          go get github.com/securego/gosec/v2/cmd/gosec
          go get -u golang.org/x/lint/golint
          go get github.com/vektra/mockery/v2/.../
          go get github.com/go-redis/redis/v8
      - name: Golang format checker
        run: |
          make fmt      
      - name: Go vet
        run: |
          make vet
      - name: Golang linting
        run: |
          make lint
      - name: Golang security checker
        run: |
          make sec
      - name: Build linux binaries
        run: |
          make build-linux-binaries
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'
      - name: Install go dependencies
        run: |
          go mod download
          go get github.com/vektra/mockery/v2/.../
          go get github.com/go-redis/redis/v8
      - name: Run unittests
        run: |
          make unit-tests
  integration_tests_kafka_redis_mongo:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - '27017:27017'
      redis:
        image: redis
        ports:
          - '6379:6379'
      zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
          - '2181:2181'
        env:
          ALLOW_ANONYMOUS_LOGIN: yes
      kafka:
        image: 'bitnami/kafka:latest'
        ports:
          - '9092:9092'
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
          KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.6'
      - name: Install mongo cli and configure
        run: |
          ls -al .
          ./samples/integration-installs/mongo.sh
      - name: Install go dependencies
        run: |
          go mod download
          go get github.com/vektra/mockery/v2/.../
          go get github.com/go-redis/redis/v8
      - name: Run integration tests
        run: |
          make integration-tests
