name: Build and run analysis steps against the D3E services

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.5'
      - name: Install go dependencies
        run: |
          go get -u golang.org/x/lint/golint
      - name: Golang format checker
        run: |
          gofmt
      - name: Go vet
        run: |
          make vet
      - name: Golang linting
        run: |
          golint
      - name: Golang security checker
        run: |
          gosec
  #    - name: Build linux binaries
   #     run: |
    #      make build-linux-binaries
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.5'
      - name: Install go dependencies
        run: |
          go get github.com/stretchr/testify/assert
      - name: Run unittests
        run: |
          go test .
