name: Test

on:
  push:
    branches:
      - master
      - main
      
jobs:
  test:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
        with:
          stable: 'false'
          go-version: 1.14.5
      - name: test
        run: go test ./...
